export const CATEGORIA_ADD = 'CATEGORIA_ADD';
export const CATEGORIA_UPDATE = 'CATEGORIA_UPDATE';
export const CATEGORIA_DELETE = 'CATEGORIA_DELETE';
export const CATEGORIA_DETAIL = 'CATEGORIA_DETAIL';
export const CATEGORIA_ERROR = 'CATEGORIA_ERROR';
export const CATEGORIA_ALL_REQUEST = 'CATEGORIA_ALL_REQUEST';
export const CATEGORIA_ALL_SUCCESS = 'CATEGORIA_ALL_SUCCESS';
