export const CHAMADO_ADD = 'CHAMADO_ADD';
export const CHAMADO_UPDATE = 'CHAMADO_UPDATE';
export const CHAMADO_DELETE = 'CHAMADO_DELETE';
export const CHAMADO_DETAIL = 'CHAMADO_DETAIL';
export const CHAMADO_ERROR = 'CHAMADO_ERROR';
export const CHAMADO_ALL_REQUEST = 'CHAMADO_ALL_REQUEST';
export const CHAMADO_ALL_SUCCESS = 'CHAMADO_ALL_SUCCESS';
export const CHAMADO_ADD_INTERACT = 'CHAMADO_ADD_INTERACT';

