export const MODULO_ADD = 'MODULO_ADD';
export const MODULO_UPDATE = 'MODULO_UPDATE';
export const MODULO_DELETE = 'MODULO_DELETE';
export const MODULO_DETAIL = 'MODULO_DETAIL';
export const MODULO_ERROR = 'MODULO_ERROR';
export const MODULO_ALL_REQUEST = 'MODULO_ALL_REQUEST';
export const MODULO_ALL_SUCCESS = 'MODULO_ALL_SUCCESS';
