export const USUARIO_ADD = 'USUARIO_ADD';
export const USUARIO_UPDATE = 'USUARIO_UPDATE';
export const USUARIO_DELETE = 'USUARIO_DELETE';
export const USUARIO_DETAIL = 'USUARIO_DETAIL';
export const USUARIO_ERROR = 'USUARIO_ERROR';
export const USUARIO_ALL_REQUEST = 'USUARIO_ALL_REQUEST';
export const USUARIO_ALL_SUCCESS = 'USUARIO_ALL_SUCCESS';
